# Generated by Django 2.1 on 2019-12-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list',
            table='todo',
        ),
    ]
